services:
  file-server:
    build: .
    container_name: file_server
    ports:
      - "8080:8080"
    volumes:
      - ./share:/app/share
    restart: unless-stopped
    networks:
      - internal_net

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http_client
    command: ["python", "-u", "client_new.py"]
    depends_on:
      - file-server
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
